trigger:
  - main

pool:
  name: 'NewAgentForProject'   # Default agent

  # ---------------------------
  # Checkout Azure Repo
  # ---------------------------
# Define GitHub repository as a resource
resources:
  repositories:
    - repository: githubRepo        # local reference name
      type: github
      name: Ravi-126/TestDemo   # GitHub username / repo
      endpoint: GitHubServiceConnection

steps:
  # ---------------------------
  # Checkout the GitHub repository
  - checkout: githubRepo
  # ---------------------------
  # Maven Build
  # ---------------------------
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21'
      jdkArchitectureOption: 'x64'

  # ---------------------------
  # Run Cucumber Tests using Runner Class
  # ---------------------------
  - script: |
      echo "Running Cucumber Tests Using TestRunner"
      mvn -Dtest=runner.WebTestRunner test
    displayName: "Execute Cucumber Runner"

  # ---------------------------
  # Publish Cucumber HTML Report
  # ---------------------------

  # Ensure Cucumber report folder exists (to prevent pipeline errors)
  - script: |
      echo "Ensuring Cucumber report folder exists"
      if not exist target\cucumber-reports mkdir target\cucumber-reports
    displayName: "Ensure Cucumber Report Folder Exists"

  # ---------------------------
  # Debug: list target folder contents
  - script: |
      echo "Contents of target folder:"
      dir target
    displayName: "Debug Target Folder"


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'target/cucumber-reports'  # folder containing the HTML report
      artifact: 'CucumberReport'
      publishLocation: 'pipeline'
    displayName: "Publish Cucumber HTML Report"